package com.jbpm;

import org.drools.runtime.process.WorkflowProcessInstance;
import com.plugin.jbpm.drools.model.Hour;

rule "it is morning before lunch"
	ruleflow-group "fp_task"
	when
		$process: WorkflowProcessInstance()
		Hour(value >=6 && < 12) from $process.getVariable("hourOfDay")
	then 
		$process.setVariable("period", "morning");
end


rule "it is afternoon before dinner"
	ruleflow-group "fp_task"
	when
		$process: WorkflowProcessInstance()
		Hour(value >= 12 && < 20) from $process.getVariable("hourOfDay")
	then 
		$process.setVariable("period", "afternoon");
end

rule "it is night afterwards"
	ruleflow-group "fp_task"
	when
		$process: WorkflowProcessInstance()
		Hour(value >= 20 || < 6) from $process.getVariable("hourOfDay")
	then 
		$process.setVariable("period", "night");
end